version: '2.0'
services:
  mirror-slow-mock:
    build: mirror-slow-mock
    container_name: mirror-slow-mock
  mirror-fast-mock:
    build: mirror-fast-mock
    container_name: mirror-fast-mock
  flexo-server:
    build: flexo-server
    container_name: flexo-server
    depends_on:
      - mirror-slow-mock
      - mirror-fast-mock
  flexo-client:
    build: flexo-client
    container_name: flexo-client
    depends_on:
      - flexo-server
      - mirror-slow-mock
      - mirror-fast-mock
