version: '3.7'
services:
  mirror-slow-mock:
    build: mirror-slow-mock
    container_name: mirror-slow-mock
  mirror-low-bandwidth-mock:
    build: mirror-low-bandwidth-mock
    container_name: mirror-low-bandwidth-mock
  mirror-fast-mock:
    build: mirror-fast-mock
    container_name: mirror-fast-mock
  flexo-server:
    build: flexo-server
    container_name: flexo-server
    depends_on:
      - mirror-slow-mock
      - mirror-fast-mock
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7878/status || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s
  flexo-server-slow-primary:
    build: flexo-server-slow-primary
    container_name: flexo-server-slow-primary
    depends_on:
      - mirror-fast-mock
      - mirror-low-bandwidth-mock
  flexo-client:
    build: flexo-client
    container_name: flexo-client
    depends_on:
      - flexo-server
      - mirror-slow-mock
      - mirror-fast-mock
