version: '3.7'
services:
  mirror-fast-mock:
    build: mirror-fast-mock
    container_name: mirror-fast-mock
  flexo-server:
    build: flexo-server
    container_name: flexo-server
    depends_on:
      - mirror-fast-mock
    ports:
      - 7979:7878
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7878/status || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s
