# Note that cpcache relies on the directory structure that is created in
# /var/cache/cpcache during install. If you change this setting, copy the
# contents to the new directory and make sure user cpcache has read- and
# write-access.
cache_directory = "/var/cache/flexo/pkg"

# After the mirrorlist was fetched from a remote JSON endpoint, this JSON file
# will be persisted on the local file system so that it can serve as a backup in
# case the remote endpoint cannot be reached.
mirrorlist_fallback_file = "/var/cache/flexo/state/mirrorlist.json"

# The port to listen on.
port = 7878

# The selection method to choose a mirror. Valid values are:
#   "auto": In order to attempt to find suitable mirrors automatically.
#           With this method, performance tests are run on the official mirrors
#           to select only sufficiently fast mirrors.
#   "predefined": To only choose the mirrors defined for the variable
#                 mirrors_predefined (see below).
mirror_selection_method = "auto"


# In case no suitable mirror could be found automatically, cpcache will attempt
# to download files from the following mirrors. This list can be empty if
# mirror_selection_method has been set to "auto".
mirrors_predefined = [
    "https://mirror.yandex.ru/archlinux/"
]

# The method to choose suitable mirrors automatically may not always work
# perfectly. If one of the automatically chosen mirrors turns out to be slow or
# unstable, add it to this list.
mirrors_blacklist = [ ]

# Various settings that apply if mirror_selection_method has been set to "auto".
[mirrors_auto]
    # Used for testing purposes.
    # max_speed_limit = 102400
    # only use mirrors with HTTPS support.
    https_required = true
    # mirrors must support IPv4.
    ipv4 = true
    # mirrors must support IPv6.
    ipv6 = true
    # The maximum score allowed from a mirror. See
    # https://www.archlinux.org/mirrors/status/ for an explanation of this
    # metric.
    max_score = 2.5
    # The maximum number of mirrors to use and test for latency. Increasing this
    # number will also increase the startup time of flexo (due to the number of
    # latency tests), but it might also give you a faster mirror.
    num_mirrors = 8
    # Valid values for this setting include "sort" and "random".  After the
    # mirrors have been filtered according to your chosen criteria (e.g. ipv6
    # supported, score not more than 2.5), you will most likely still have more
    # than num_mirrors mirrors. This setting determines the strategy for
    # choosing num_mirrors out of those mirrors. With "sort", the mirrors are
    # sorted by their score and the first num_mirrors mirrors are selected. With
    # "random", a random selection of num_mirrors are selected.  Choose "sort"
    # if you want to increase the likelihood of having a fast and up-to-date
    # mirror. Choose "random" if you want to avoid to always use the same
    # mirror, and instead balance the load among many mirrors.
    mirrors_random_or_sort = "sort"
    # timeout, in milliseconds, when testing the mirrors' performance.
    # Mirros which exceed the timeout will not be considered further, regardless
    # of their score.
    timeout = 350
