cache_directory = "/var/cache/flexo"
port = 7878
mirror_selection_method = "auto"
mirrors_predefined = [ ]
mirrors_blacklist = [ ]
localrepos = [ ]

# Various settings that apply if mirror_selection_method has been set to "auto".
[mirrors_auto]
    # Used for testing purposes.
    # max_speed_limit = 102400
    # only use mirrors with HTTPS support.
    https_required = true
    # mirrors must support IPv4.
    ipv4 = true
    # mirrors must support IPv6.
    ipv6 = true
    # The maximum score allowed from a mirror. See
    # https://www.archlinux.org/mirrors/status/ for an explanation of this
    # metric.
    max_score = 2.5
    # The maximum number of mirrors to use and test for latency. Increasing this
    # number will also increase the startup time of cpcache (due to the latency
    # tests), but it might also give you a faster mirror.
    num_mirrors = 8
    # Valid values for this setting include "sort" and "random".  After the
    # mirrors have been filtered according to your chosen criteria (e.g. ipv6
    # supported, score not more than 2.5), you will most likely still have more
    # than num_mirrors mirrors. This setting determines the strategy for
    # choosing num_mirrors out of those mirrors. With "sort", the mirrors are
    # sorted by their score and the first num_mirrors mirrors are selected. With
    # "random", a random selection of num_mirrors are selected.  Choose "sort"
    # if you want to increase the likelihood of having a fast and up-to-date
    # mirror. Choose "random" if you want to avoid to always use the same
    # mirror, and instead balance the load among many mirrors.
    mirrors_random_or_sort = "sort"
    # timeout, in milliseconds, when testing the mirrors' performance.
    # Mirros which exceed the timeout will not be considered further, regardless
    # of their score.
    timeout = 350
    # If mirrors are chosen automatically, this setting allows to define how
    # often the selection process should be repeated. Valid values are positive
    # numbers (for instance, 24 to rerun the selection process every 24 hours),
    # and -1 to never re-run the selection process.
    test_interval = 24
